# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.30

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = C:\Qt\Tools\CMake_64\bin\cmake.exe

# The command to remove a file.
RM = C:\Qt\Tools\CMake_64\bin\cmake.exe -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = C:\Users\Emeline\Documents\CPP_Scripts

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = C:\Users\Emeline\Documents\CPP_Scripts

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	C:\Qt\Tools\CMake_64\bin\cmake-gui.exe -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	C:\Qt\Tools\CMake_64\bin\cmake.exe --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\Emeline\Documents\CPP_Scripts\CMakeFiles C:\Users\Emeline\Documents\CPP_Scripts\\CMakeFiles\progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\Emeline\Documents\CPP_Scripts\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named MyQtApp

# Build rule for target.
MyQtApp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 MyQtApp
.PHONY : MyQtApp

# fast build rule for target.
MyQtApp/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\MyQtApp.dir\build.make CMakeFiles/MyQtApp.dir/build
.PHONY : MyQtApp/fast

#=============================================================================
# Target rules for targets named MyQtApp_autogen_timestamp_deps

# Build rule for target.
MyQtApp_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 MyQtApp_autogen_timestamp_deps
.PHONY : MyQtApp_autogen_timestamp_deps

# fast build rule for target.
MyQtApp_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\MyQtApp_autogen_timestamp_deps.dir\build.make CMakeFiles/MyQtApp_autogen_timestamp_deps.dir/build
.PHONY : MyQtApp_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named MyQtApp_autogen

# Build rule for target.
MyQtApp_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 MyQtApp_autogen
.PHONY : MyQtApp_autogen

# fast build rule for target.
MyQtApp_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\MyQtApp_autogen.dir\build.make CMakeFiles/MyQtApp_autogen.dir/build
.PHONY : MyQtApp_autogen/fast

MyQtApp_autogen/mocs_compilation.obj: MyQtApp_autogen/mocs_compilation.cpp.obj
.PHONY : MyQtApp_autogen/mocs_compilation.obj

# target to build an object file
MyQtApp_autogen/mocs_compilation.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\MyQtApp.dir\build.make CMakeFiles/MyQtApp.dir/MyQtApp_autogen/mocs_compilation.cpp.obj
.PHONY : MyQtApp_autogen/mocs_compilation.cpp.obj

MyQtApp_autogen/mocs_compilation.i: MyQtApp_autogen/mocs_compilation.cpp.i
.PHONY : MyQtApp_autogen/mocs_compilation.i

# target to preprocess a source file
MyQtApp_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\MyQtApp.dir\build.make CMakeFiles/MyQtApp.dir/MyQtApp_autogen/mocs_compilation.cpp.i
.PHONY : MyQtApp_autogen/mocs_compilation.cpp.i

MyQtApp_autogen/mocs_compilation.s: MyQtApp_autogen/mocs_compilation.cpp.s
.PHONY : MyQtApp_autogen/mocs_compilation.s

# target to generate assembly for a file
MyQtApp_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\MyQtApp.dir\build.make CMakeFiles/MyQtApp.dir/MyQtApp_autogen/mocs_compilation.cpp.s
.PHONY : MyQtApp_autogen/mocs_compilation.cpp.s

src/Controller/Game.obj: src/Controller/Game.cpp.obj
.PHONY : src/Controller/Game.obj

# target to build an object file
src/Controller/Game.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\MyQtApp.dir\build.make CMakeFiles/MyQtApp.dir/src/Controller/Game.cpp.obj
.PHONY : src/Controller/Game.cpp.obj

src/Controller/Game.i: src/Controller/Game.cpp.i
.PHONY : src/Controller/Game.i

# target to preprocess a source file
src/Controller/Game.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\MyQtApp.dir\build.make CMakeFiles/MyQtApp.dir/src/Controller/Game.cpp.i
.PHONY : src/Controller/Game.cpp.i

src/Controller/Game.s: src/Controller/Game.cpp.s
.PHONY : src/Controller/Game.s

# target to generate assembly for a file
src/Controller/Game.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\MyQtApp.dir\build.make CMakeFiles/MyQtApp.dir/src/Controller/Game.cpp.s
.PHONY : src/Controller/Game.cpp.s

src/Model/Card.obj: src/Model/Card.cpp.obj
.PHONY : src/Model/Card.obj

# target to build an object file
src/Model/Card.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\MyQtApp.dir\build.make CMakeFiles/MyQtApp.dir/src/Model/Card.cpp.obj
.PHONY : src/Model/Card.cpp.obj

src/Model/Card.i: src/Model/Card.cpp.i
.PHONY : src/Model/Card.i

# target to preprocess a source file
src/Model/Card.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\MyQtApp.dir\build.make CMakeFiles/MyQtApp.dir/src/Model/Card.cpp.i
.PHONY : src/Model/Card.cpp.i

src/Model/Card.s: src/Model/Card.cpp.s
.PHONY : src/Model/Card.s

# target to generate assembly for a file
src/Model/Card.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\MyQtApp.dir\build.make CMakeFiles/MyQtApp.dir/src/Model/Card.cpp.s
.PHONY : src/Model/Card.cpp.s

src/Model/DeckCards.obj: src/Model/DeckCards.cpp.obj
.PHONY : src/Model/DeckCards.obj

# target to build an object file
src/Model/DeckCards.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\MyQtApp.dir\build.make CMakeFiles/MyQtApp.dir/src/Model/DeckCards.cpp.obj
.PHONY : src/Model/DeckCards.cpp.obj

src/Model/DeckCards.i: src/Model/DeckCards.cpp.i
.PHONY : src/Model/DeckCards.i

# target to preprocess a source file
src/Model/DeckCards.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\MyQtApp.dir\build.make CMakeFiles/MyQtApp.dir/src/Model/DeckCards.cpp.i
.PHONY : src/Model/DeckCards.cpp.i

src/Model/DeckCards.s: src/Model/DeckCards.cpp.s
.PHONY : src/Model/DeckCards.s

# target to generate assembly for a file
src/Model/DeckCards.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\MyQtApp.dir\build.make CMakeFiles/MyQtApp.dir/src/Model/DeckCards.cpp.s
.PHONY : src/Model/DeckCards.cpp.s

src/Model/Person/Bank.obj: src/Model/Person/Bank.cpp.obj
.PHONY : src/Model/Person/Bank.obj

# target to build an object file
src/Model/Person/Bank.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\MyQtApp.dir\build.make CMakeFiles/MyQtApp.dir/src/Model/Person/Bank.cpp.obj
.PHONY : src/Model/Person/Bank.cpp.obj

src/Model/Person/Bank.i: src/Model/Person/Bank.cpp.i
.PHONY : src/Model/Person/Bank.i

# target to preprocess a source file
src/Model/Person/Bank.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\MyQtApp.dir\build.make CMakeFiles/MyQtApp.dir/src/Model/Person/Bank.cpp.i
.PHONY : src/Model/Person/Bank.cpp.i

src/Model/Person/Bank.s: src/Model/Person/Bank.cpp.s
.PHONY : src/Model/Person/Bank.s

# target to generate assembly for a file
src/Model/Person/Bank.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\MyQtApp.dir\build.make CMakeFiles/MyQtApp.dir/src/Model/Person/Bank.cpp.s
.PHONY : src/Model/Person/Bank.cpp.s

src/Model/Person/Person.obj: src/Model/Person/Person.cpp.obj
.PHONY : src/Model/Person/Person.obj

# target to build an object file
src/Model/Person/Person.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\MyQtApp.dir\build.make CMakeFiles/MyQtApp.dir/src/Model/Person/Person.cpp.obj
.PHONY : src/Model/Person/Person.cpp.obj

src/Model/Person/Person.i: src/Model/Person/Person.cpp.i
.PHONY : src/Model/Person/Person.i

# target to preprocess a source file
src/Model/Person/Person.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\MyQtApp.dir\build.make CMakeFiles/MyQtApp.dir/src/Model/Person/Person.cpp.i
.PHONY : src/Model/Person/Person.cpp.i

src/Model/Person/Person.s: src/Model/Person/Person.cpp.s
.PHONY : src/Model/Person/Person.s

# target to generate assembly for a file
src/Model/Person/Person.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\MyQtApp.dir\build.make CMakeFiles/MyQtApp.dir/src/Model/Person/Person.cpp.s
.PHONY : src/Model/Person/Person.cpp.s

src/Model/Person/Player.obj: src/Model/Person/Player.cpp.obj
.PHONY : src/Model/Person/Player.obj

# target to build an object file
src/Model/Person/Player.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\MyQtApp.dir\build.make CMakeFiles/MyQtApp.dir/src/Model/Person/Player.cpp.obj
.PHONY : src/Model/Person/Player.cpp.obj

src/Model/Person/Player.i: src/Model/Person/Player.cpp.i
.PHONY : src/Model/Person/Player.i

# target to preprocess a source file
src/Model/Person/Player.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\MyQtApp.dir\build.make CMakeFiles/MyQtApp.dir/src/Model/Person/Player.cpp.i
.PHONY : src/Model/Person/Player.cpp.i

src/Model/Person/Player.s: src/Model/Person/Player.cpp.s
.PHONY : src/Model/Person/Player.s

# target to generate assembly for a file
src/Model/Person/Player.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\MyQtApp.dir\build.make CMakeFiles/MyQtApp.dir/src/Model/Person/Player.cpp.s
.PHONY : src/Model/Person/Player.cpp.s

src/View/View.obj: src/View/View.cpp.obj
.PHONY : src/View/View.obj

# target to build an object file
src/View/View.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\MyQtApp.dir\build.make CMakeFiles/MyQtApp.dir/src/View/View.cpp.obj
.PHONY : src/View/View.cpp.obj

src/View/View.i: src/View/View.cpp.i
.PHONY : src/View/View.i

# target to preprocess a source file
src/View/View.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\MyQtApp.dir\build.make CMakeFiles/MyQtApp.dir/src/View/View.cpp.i
.PHONY : src/View/View.cpp.i

src/View/View.s: src/View/View.cpp.s
.PHONY : src/View/View.s

# target to generate assembly for a file
src/View/View.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\MyQtApp.dir\build.make CMakeFiles/MyQtApp.dir/src/View/View.cpp.s
.PHONY : src/View/View.cpp.s

src/main.obj: src/main.cpp.obj
.PHONY : src/main.obj

# target to build an object file
src/main.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\MyQtApp.dir\build.make CMakeFiles/MyQtApp.dir/src/main.cpp.obj
.PHONY : src/main.cpp.obj

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\MyQtApp.dir\build.make CMakeFiles/MyQtApp.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\MyQtApp.dir\build.make CMakeFiles/MyQtApp.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... MyQtApp_autogen
	@echo ... MyQtApp_autogen_timestamp_deps
	@echo ... MyQtApp
	@echo ... MyQtApp_autogen/mocs_compilation.obj
	@echo ... MyQtApp_autogen/mocs_compilation.i
	@echo ... MyQtApp_autogen/mocs_compilation.s
	@echo ... src/Controller/Game.obj
	@echo ... src/Controller/Game.i
	@echo ... src/Controller/Game.s
	@echo ... src/Model/Card.obj
	@echo ... src/Model/Card.i
	@echo ... src/Model/Card.s
	@echo ... src/Model/DeckCards.obj
	@echo ... src/Model/DeckCards.i
	@echo ... src/Model/DeckCards.s
	@echo ... src/Model/Person/Bank.obj
	@echo ... src/Model/Person/Bank.i
	@echo ... src/Model/Person/Bank.s
	@echo ... src/Model/Person/Person.obj
	@echo ... src/Model/Person/Person.i
	@echo ... src/Model/Person/Person.s
	@echo ... src/Model/Person/Player.obj
	@echo ... src/Model/Person/Player.i
	@echo ... src/Model/Person/Player.s
	@echo ... src/View/View.obj
	@echo ... src/View/View.i
	@echo ... src/View/View.s
	@echo ... src/main.obj
	@echo ... src/main.i
	@echo ... src/main.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

